# Generated by Django 2.2.12 on 2020-05-12 21:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Data zamówienia')),
                ('total_account', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Do zapłaty')),
                ('full_name', models.CharField(max_length=100, verbose_name='Imię i nazwisko')),
                ('city', models.CharField(max_length=40, verbose_name='Miejscowość')),
                ('street', models.CharField(max_length=40, verbose_name='Ulica')),
                ('number_of_house', models.CharField(max_length=40, verbose_name='Numer domu / numer mieszkania')),
                ('phone', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Numer kontaktowy')),
                ('paid', models.BooleanField(default=False, verbose_name='Zamówienie opłacono')),
                ('paid_method', models.CharField(choices=[('cash', 'Gotówka'), ('card_payment', 'Płatność kartą'), ('transfer', 'Przelew')], max_length=20, verbose_name='Metoda płatności')),
            ],
        ),
        migrations.CreateModel(
            name='OrderIt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meat', models.CharField(blank=True, choices=[('chicken', 'Kurczak'), ('veal', 'Cielęcina'), ('mix', 'Mix')], max_length=20, null=True, verbose_name='Mięso')),
                ('chips', models.CharField(blank=True, choices=[('chips', 'Frytki'), ('slices', 'Talarki'), ('wedges', 'Łódeczki'), ('potato', 'Ziemniaki')], max_length=20, null=True, verbose_name='Frytki')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cena')),
                ('meat', models.CharField(blank=True, choices=[('chicken', 'Kurczak'), ('veal', 'Cielęcina'), ('mix', 'Mix')], max_length=20, null=True, verbose_name='Mięso')),
                ('chips', models.CharField(blank=True, choices=[('chips', 'Frytki'), ('slices', 'Talarki'), ('wedges', 'Łódeczki'), ('potato', 'Ziemniaki')], max_length=20, null=True, verbose_name='Frytki')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cart', to='order.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='pizza.UUID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSauce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_sauce', to='order.OrderItem')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_sauce', to='pizza.Sauce_SIZE')),
            ],
        ),
    ]
